######################################################################
# Automatically generated by qmake (1.04a) Wed Dec 17 17:06:25 2003
######################################################################

TEMPLATE = app

CONFIG      += qt warn_off staticlib link_pkgconfig

DEFINES     += HAVE_QT4
#DEFINES    += HAVE_QT4 CWDEBUG 

INCLUDEPATH += ./include
PKGCONFIG   +=  
#PKGCONFIG   +=  libxml-2.0 gsl proj-4 gd tiff z

LIBS        +=

# Input
HEADERS += 
SOURCES += ./MSG_navigation_v1.01.c

#install
target.path += /home/meteo/bin
INSTALLS += target
